# escape=`

# renovate: datasource=github-releases depName=docuum lookupName=stepchowfun/docuum
ARG DOCUUM_VERSION=0.22.4

# renovate: datasource=github-releases depName=docker lookupName=moby/moby
ARG DOCKER_VERSION=23.0.6

FROM mcr.microsoft.com/windows/nanoserver:ltsc2022@sha256:0e847c01d2565d9abba138dd6bd1eaf5e8c6076d43ecfaff50e94f142899b9f1

USER ContainerAdministrator

LABEL maintainer="Michael Kriese <michael.kriese@visualon.de>" `
  org.opencontainers.image.authors="Michael Kriese <michael.kriese@visualon.de>" `
  org.opencontainers.image.licenses="MIT" `
  org.opencontainers.image.source="https://github.com/visualon/docker-docuum" `
  org.opencontainers.image.url="https://github.com/visualon/docker-docuum"

ENTRYPOINT ["/bin/docuum"]

#ENV DOCKER_HOST=npipe:////./pipe/docker_engine


RUN mkdir bin
RUN setx /M PATH "c:\bin;%PATH%" > nul

ARG DOCKER_VERSION
RUN `
  curl -sSfLo file.zip https://download.docker.com/win/static/stable/x86_64/docker-%DOCKER_VERSION%.zip `
  && tar -C /bin -oxzf file.zip --strip 1 docker/docker.exe `
  && del /f file.zip `
  && docker --version

ARG DOCUUM_VERSION
LABEL org.opencontainers.image.version="${DOCUUM_VERSION}"

RUN `
	curl -sSfLo bin/docuum.exe https://github.com/stepchowfun/docuum/releases/download/v%DOCUUM_VERSION%/docuum-x86_64-pc-windows-msvc.exe `
  && docuum --version
