# escape=`

# renovate: datasource=github-releases depName=docuum packageName=stepchowfun/docuum
ARG DOCUUM_VERSION=0.27.0

# renovate: datasource=github-releases depName=docker packageName=moby/moby
ARG DOCKER_VERSION=28.5.2

FROM mcr.microsoft.com/windows/nanoserver:ltsc2025@sha256:af9cf5183e68ff0beee87a795e5761ef9143fc6ee7e3d785b5920eda6f5e03fb AS build

RUN mkdir tmp && mkdir bin

ARG DOCKER_VERSION
RUN `
  curl -sSfLo tmp/file.zip https://download.docker.com/win/static/stable/x86_64/docker-%DOCKER_VERSION%.zip `
  && tar -C /bin -oxzf tmp/file.zip --strip 1 docker/docker.exe `
  && /bin/docker --version

ARG DOCUUM_VERSION
LABEL org.opencontainers.image.version="${DOCUUM_VERSION}"

RUN `
	curl -sSfLo bin/docuum.exe https://github.com/stepchowfun/docuum/releases/download/v%DOCUUM_VERSION%/docuum-x86_64-pc-windows-msvc.exe `
  && /bin/docuum --version

FROM mcr.microsoft.com/windows/nanoserver:1809@sha256:471b97211a4d3f2e02423b7f31fd398382c2f50bb3e30c406e0c53041b516f0a

USER ContainerAdministrator

LABEL maintainer="Michael Kriese <michael.kriese@visualon.de>" `
  org.opencontainers.image.authors="Michael Kriese <michael.kriese@visualon.de>" `
  org.opencontainers.image.licenses="MIT" `
  org.opencontainers.image.source="https://github.com/visualon/docker-docuum" `
  org.opencontainers.image.url="https://github.com/visualon/docker-docuum"

ENTRYPOINT ["/bin/docuum"]

ARG DOCUUM_VERSION
LABEL org.opencontainers.image.version="${DOCUUM_VERSION}"

COPY --from=build /bin /bin
