services:
  sut:
    image: "${IMAGE}"
    entrypoint: cmd /c
    command: docuum --version && docker info
    volumes:
      - source: '\\.\pipe\docker_engine'
        target: '\\.\pipe\docker_engine'
        type: npipe
