# escape=`

# renovate: datasource=github-releases depName=docuum packageName=stepchowfun/docuum
ARG DOCUUM_VERSION=0.26.0

# renovate: datasource=github-releases depName=docker packageName=moby/moby
ARG DOCKER_VERSION=28.5.2

FROM mcr.microsoft.com/windows/nanoserver:ltsc2025@sha256:40a16c02dd07be0ef8077d405238acd5c29f2705136fab609da221e4de849b2a AS build

RUN mkdir tmp && mkdir bin

ARG DOCKER_VERSION
RUN `
  curl -sSfLo tmp/file.zip https://download.docker.com/win/static/stable/x86_64/docker-%DOCKER_VERSION%.zip `
  && tar -C /bin -oxzf tmp/file.zip --strip 1 docker/docker.exe `
  && /bin/docker --version

ARG DOCUUM_VERSION
LABEL org.opencontainers.image.version="${DOCUUM_VERSION}"

RUN `
	curl -sSfLo bin/docuum.exe https://github.com/stepchowfun/docuum/releases/download/v%DOCUUM_VERSION%/docuum-x86_64-pc-windows-msvc.exe `
  && /bin/docuum --version

FROM mcr.microsoft.com/windows/nanoserver:ltsc2025@sha256:40a16c02dd07be0ef8077d405238acd5c29f2705136fab609da221e4de849b2a

USER ContainerAdministrator

LABEL maintainer="Michael Kriese <michael.kriese@visualon.de>" `
  org.opencontainers.image.authors="Michael Kriese <michael.kriese@visualon.de>" `
  org.opencontainers.image.licenses="MIT" `
  org.opencontainers.image.source="https://github.com/visualon/docker-docuum" `
  org.opencontainers.image.url="https://github.com/visualon/docker-docuum"

ENTRYPOINT ["/bin/docuum"]

ARG DOCUUM_VERSION
LABEL org.opencontainers.image.version="${DOCUUM_VERSION}"

COPY --from=build /bin /bin
