# escape=`

# renovate: datasource=github-releases depName=docuum lookupName=stepchowfun/docuum
ARG DOCUUM_VERSION=0.25.0

# renovate: datasource=github-releases depName=docker lookupName=moby/moby
ARG DOCKER_VERSION=24.0.9

FROM mcr.microsoft.com/windows/nanoserver:ltsc2022@sha256:ac6a7571d5a404398e2f734d92f9b8f580a4fe1e6ae1820a61c5f138b1bdeff3

USER ContainerAdministrator

LABEL maintainer="Michael Kriese <michael.kriese@visualon.de>" `
  org.opencontainers.image.authors="Michael Kriese <michael.kriese@visualon.de>" `
  org.opencontainers.image.licenses="MIT" `
  org.opencontainers.image.source="https://github.com/visualon/docker-docuum" `
  org.opencontainers.image.url="https://github.com/visualon/docker-docuum"

ENTRYPOINT ["/bin/docuum"]

#ENV DOCKER_HOST=npipe:////./pipe/docker_engine


RUN mkdir bin
RUN setx /M PATH "c:\bin;%PATH%" > nul

ARG DOCKER_VERSION
RUN `
  curl -sSfLo file.zip https://download.docker.com/win/static/stable/x86_64/docker-%DOCKER_VERSION%.zip `
  && tar -C /bin -oxzf file.zip --strip 1 docker/docker.exe `
  && del /f file.zip `
  && docker --version

ARG DOCUUM_VERSION
LABEL org.opencontainers.image.version="${DOCUUM_VERSION}"

RUN `
	curl -sSfLo bin/docuum.exe https://github.com/stepchowfun/docuum/releases/download/v%DOCUUM_VERSION%/docuum-x86_64-pc-windows-msvc.exe `
  && docuum --version
