services:
  sut:
    image: "${IMAGE}"
    entrypoint: cmd /c
    command: /bin/docuum --version && /bin/docker info
    volumes:
      - source: '\\.\pipe\docker_engine'
        target: '\\.\pipe\docker_engine'
        type: npipe
